### ISSUE TITLE
一个菜鸡的自我反省 | 高渐离の屋

### ISSUE THREAD

**Issue by Gaojianli** [Gaojianli/gaojianli.github.io#3]
https://us.gaojianli.tk/about/ 

 个人简介19岁，是学生，身高是170公分，体重是74公斤。没有特别在做什么运动，也没有在健身，所以不怎么会出现衣服尺寸不合的情况。机缘巧合下从贫困的四川山区来到了大佬云集的锤雷大学，现在苟活在大佬中间瑟瑟发抖。 技能树 这个人会的不多，但是知道的不少——来自高中同学的评价  可以说是十分中肯了，没错，我就是那种啥都会一点，啥都不精的人，而且方向绝对比潇多。因此下面的列表你们看看就好：  Web前端

**Comment by DictXiong** [comment]
![我想咚一个人质](https://tools.beardic.cn/open/pic/%E4%BA%BA%E8%B4%A8%E5%88%AB%E6%80%95-%E6%88%91%E6%9D%A5%E4%BA%86-r6.jpg)
