### ISSUE TITLE
写在前面 | 高渐离の屋

### ISSUE THREAD

**Issue by Gaojianli** [Gaojianli/gaojianli.github.io#5]
https://us.gaojianli.tk/2018/06/12/%E5%86%99%E5%9C%A8%E5%89%8D%E9%9D%A2/ 

 思前想后，看见大家都有了，我还是开一个博客吧。之前一直懒得弄的原因是担心自己没有动力去写文章。但是，怎么说呢，完事开头难，人家潇都有了我怎么能没有呢！（笑）也有这么一种不服气在里面就是了。那就这样吧，希望能够坚持下去。以上

**Comment by Gaojianli** [comment]
虽然如此，但不论是数量还是博文质量都比不过潇大佬。。果然从一开始就输了个彻彻底底

**Comment by XiaoXice** [comment]
可还行
> @Gaojianli
> 虽然如此，但不论是数量还是博文质量都比不过潇大佬。。果然从一开始就输了个彻彻底底
