### ISSUE TITLE
为博客添加Gitalk评论插件 | 高渐离の屋

### ISSUE THREAD

**Issue by Gaojianli** [Gaojianli/gaojianli.github.io#6]
https://gaojianli.tk/2018/07/24/%E4%B8%BA%E5%8D%9A%E5%AE%A2%E6%B7%BB%E5%8A%A0Gitalk%E8%AF%84%E8%AE%BA%E6%8F%92%E4%BB%B6/#more 

 前言一直以来都想要给自己的博客弄个评论系统，但是hexo作为一个静态博客，本身是不可能具有这种功能的，只能仰仗第三方插件。这方面的插件也非常多，比如disqus,vline等。但这些插件都存在或多或少问题，比如注册麻烦或者干脆国内不能访问。考虑到我家长城宽带的现实，必须选择一个在各地都能流畅访问的插件，这里我选择了Gitalk. 简介先来看看官网的简介吧：  Gitalk is a modern

**Comment by XiaoXice** [comment]
我过来砸场子了 [正统解决可否评论的方法](https://blog.xice.cf/2018/07/25/使用valine为博客添加评论功能/#解决)
