### ISSUE TITLE
即日起本站域名切换到gaojianli.me | 高渐离の屋

### ISSUE THREAD

**Issue by Gaojianli** [Gaojianli/gaojianli.github.io#9]
https://blog.gaojianli.me/2018/10/15/即日起本站域名切换到gaojianli-me/ 

 一直以来，我都使用的是Freenom提供的.tk免费域名，由于功能齐全且续费免费，自然是我区区一个穷学生的首选。虽然一直有小伙伴劝我切换到一个收费域名，而且烈士墙上被无故收走域名惨案的比比皆是。但我由于个人懒惰，在加上又不是不能用的人生信条，一直就用了下来。但是就在前不久，潇却经历了一次惨痛无比的域名回收事件，Freenom在没有任何征兆、事前通知的情况下删除了他的域名（xice.cf)，而再次注

**Comment by XiaoXice** [comment]
友情链接请及时关闭

**Comment by DictXiong** [comment]
嘻嘻 昨天我去看了我的tk域名 也莫名被回收了 不过还能免费注

**Comment by XiaoXice** [comment]
> @BearDic
> 嘻嘻 昨天我去看了我的tk域名 也莫名被回收了 不过还能免费注

还是澄清一下吧，freenom的域名都是到期之后收回的，不存在莫名回收的问题，而且收回之前也会给发邮件的，我当时是没注意。自己做的死。（付费确实可以直接买免费的域名，具体可以在自己已经取得免费域名之后再去搜索，发现域名可被注册，只是需要花钱）

**Comment by DictXiong** [comment]
> @XiaoXice
> > @BearDic
> > 嘻嘻 昨天我去看了我的tk域名 也莫名被回收了 不过还能免费注
> 
> 还是澄清一下吧，freenom的域名都是到期之后收回的，不存在莫名回收的问题，而且收回之前也会给发邮件的，我当时是没注意。自己做的死。（付费确实可以直接买免费的域名，具体可以在自己已经取得免费域名之后再去搜索，发现域名可被注册，只是需要花钱）

但确实我的域名被收回了且没有收到任何邮件通知, 如图. 当初两个域名是同时注册的, 现在只剩下一个.


![](https://i.loli.net/2019/01/16/5c3e0d5cc482f.jpg)

**Comment by BearDic** [comment]
> @XiaoXice
> > @BearDic
> > 嘻嘻 昨天我去看了我的tk域名 也莫名被回收了 不过还能免费注
> 
> 还是澄清一下吧，freenom的域名都是到期之后收回的，不存在莫名回收的问题，而且收回之前也会给发邮件的，我当时是没注意。自己做的死。（付费确实可以直接买免费的域名，具体可以在自己已经取得免费域名之后再去搜索，发现域名可被注册，只是需要花钱）

但确实我的域名被收回了且没有收到任何邮件通知, 如图. 当初两个域名是同时注册的, 现在只剩下一个.


![](https://i.loli.net/2019/01/16/5c3e0d5cc482f.jpg)
